**1.5 [Scipy : high-level scientific computing](http://scipy-lectures.org/intro/scipy.html)**

> **Scipy**
>
>The [scipy](https://docs.scipy.org/doc/scipy/reference/index.html#module-scipy) package contains various toolboxes dedicated to common issues in scientific computing. Its different submodules correspond to different applications, such as interpolation, integration, optimization, image processing, statistics, special functions, etc.

The standard way of importing Numpy and these Scipy modules is:

In [1]:
import numpy as np
from scipy import stats  # same for other sub-modules

# 1.5.1. File input/output: [scipy.io](https://docs.scipy.org/doc/scipy/reference/tutorial/io.html#module-scipy.io)

**Matlab files**: Loading and saving:

In [2]:
from scipy import io as spio

a = np.ones((3, 3))
spio.savemat('data/file.mat', {'a': a})  # savemat expects a dictionary
data = spio.loadmat('data/file.mat')
data

{'__header__': b'MATLAB 5.0 MAT-file Platform: posix, Created on: Thu Aug 29 23:22:17 2019',
 '__version__': '1.0',
 '__globals__': [],
 'a': array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])}

In [3]:
data['a']

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**Image files**: Reading images:

In [10]:
from scipy import misc

misc.imread('data/fname.png')  

import matplotlib.pyplot as plt
plt.imread('data/fname.png') 

/home/qinjh/workspace/python/DataAnalysisWithPython/.venv/lib/python3.7/site-packages/ipykernel_launcher.py:3: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  This is separate from the ipykernel package so we can avoid doing imports until


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        ...,
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        ...,
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        ...,
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       ...,

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        ...,
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        ...,
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        ...,
        [1., 1., 1., 1.],
        [1., 1.

# 1.5.2. Special functions: scipy.special
Special functions are transcendental functions. The docstring of the scipy.special module is well-written, so we won’t list all functions here. Frequently used ones are:

- Bessel function, such as **scipy.special.jn()** (nth integer order Bessel function)
- Elliptic function (**scipy.special.ellipj()** for the Jacobian elliptic function, …)
- Gamma function: **scipy.special.gamma()**, also note **scipy.special.gammaln()** which will give the log of Gamma to a higher numerical precision.
- Erf, the area under a Gaussian curve: **scipy.special.erf()**

# 1.5.3. Linear algebra operations: scipy.linalg
 The [scipy.linalg](https://docs.scipy.org/doc/scipy/reference/linalg.html#module-scipy.linalg) module provides standard linear algebra operations, relying on an underlying efficient implementation (BLAS, LAPACK).

- The [scipy.linalg.det()](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.det.html#scipy.linalg.det) function computes the determinant of a square matrix （计算矩阵的行列式:
 

In [15]:
from scipy import linalg
arr = np.array([[1, 2],   [3, 4]]) 
linalg.det(arr)  #  1 * 4 - 2 * 3

-2.0

In [17]:
arr = np.array([[3, 2],    [6, 4]])
linalg.det(arr)

0.0

In [19]:
linalg.det(np.ones((3, 3)))

0.0

In [20]:
linalg.det(np.ones((3, 4)))

ValueError: expected square matrix

- The [scipy.linalg.inv()](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.inv.html#scipy.linalg.inv) function computes the inverse of a square matrix:

> **逆矩阵(inverse matrix)的概念及其意义**
>
>逆矩阵是经常遇到的一个概念。教科书中讲解了逆矩阵的求法，但是没有说清楚为何需要逆矩阵，逆矩阵的意义是什么。逆矩阵可以类比成数字的倒数，比如数字5的倒数是 `1/5`，矩阵 `A` 的“倒数”是 `A` 的逆矩阵。`5*(1/5)=1`,  `A*（A的逆矩阵） = I`，`I` 是单位矩阵。
>
>引入逆矩阵的原因之一是用来实现矩阵的除法。比如有矩阵`X`，`A`，`B`，其中 `X*A = B`，我们要求X矩阵的值。本能来说，我们只需要将 `B/A` 就可以得到X矩阵了。但是对于矩阵来说，不存在直接相除的概念。我们需要借助逆矩阵，间接实现矩阵的除法。具体的做法是等式两边在相同位置同时乘以矩阵A的逆矩阵，如下所示，`X*A*（A的逆矩阵）= B*（A的逆矩阵）` 。由于 `A*（A的逆矩阵） = I`，即单位矩阵，任何矩阵乘以单位矩阵的结果都是其本身。所以，我们可以得到 `X =  B*（A的逆矩阵）`。
>
>以一个具体的例子来看，链接为https://www.mathsisfun.com/algebra/matrix-inverse.html 。假设一帮孩子和家长出去旅游，去程坐的是bus，小孩票价为3元，家长票价为3.2元；回程坐的是Train，小孩票价为3.5元，家长票价为3.6元。问题是分别求小孩和家长的人数。我们就可以用下列矩阵求之。

<div>
    <img src="https://img-blog.csdn.net/20150917000301517?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQv/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center">
    <img src="https://img-blog.csdn.net/20150917000735526?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQv/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center">
    <img src="https://img-blog.csdn.net/20150917000741839?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQv/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center">
</div>    

In [22]:
arr = np.array([[1, 2],
                [3, 4]])
iarr = linalg.inv(arr)
iarr

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [23]:
np.allclose(np.dot(arr, iarr), np.eye(2))


True

Finally computing the inverse of a singular matrix (its determinant is zero) will raise LinAlgError:



In [24]:
arr = np.array([[3, 2],
                [6, 4]])
linalg.inv(arr) 

LinAlgError: singular matrix

- More advanced operations are available, for example singular-value decomposition (SVD):



In [25]:
arr = np.arange(9).reshape((3, 3)) + np.diag([1, 0, 1])
uarr, spec, vharr = linalg.svd(arr)


The resulting array spectrum is:



In [26]:
spec

array([14.88982544,  0.45294236,  0.29654967])

The original matrix can be re-composed by matrix multiplication of the outputs of svd with `np.dot`:



In [27]:
sarr = np.diag(spec)
svd_mat = uarr.dot(sarr).dot(vharr)
np.allclose(svd_mat, arr)

True

SVD is commonly used in statistics and signal processing. Many other standard decompositions (QR, LU, Cholesky, Schur), as well as solvers for linear systems, are available in `scipy.linalg`.

# 1.5.4. Interpolation: scipy.interpolate

[scipy.interpolate](https://docs.scipy.org/doc/scipy/reference/interpolate.html#module-scipy.interpolate) is useful for fitting a function from experimental data and thus evaluating points where no measure exists. The module is based on the [FITPACK Fortran subroutines](http://www.netlib.org/dierckx/index.html).

By imagining experimental data close to a sine function:

In [28]:
measured_time = np.linspace(0, 1, 10)
noise = (np.random.random(10)*2 - 1) * 1e-1
measures = np.sin(2 * np.pi * measured_time) + noise

[scipy.interpolate.interp1d](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp1d.html#scipy.interpolate.interp1d) can build a linear interpolation function:

In [29]:
from scipy.interpolate import interp1d
linear_interp = interp1d(measured_time, measures)

Then the result can be evaluated at the time of interest:

In [30]:
interpolation_time = np.linspace(0, 1, 50)
linear_results = linear_interp(interpolation_time)



A cubic interpolation can also be selected by providing the kind optional keyword argument:

In [31]:
cubic_interp = interp1d(measured_time, measures, kind='cubic')
cubic_results = cubic_interp(interpolation_time)

# 1.5.5. Optimization and fit: scipy.optimize