# 4. numpy创建数组

In [9]:
import numpy as np

list = [1,2,3,4]
array = np.array(list)

print(array)

[1 2 3 4]


**数据类型**
- dtype=np.int
- dtype=np.float

In [4]:
array = np.array(list, dtype=np.int)

print(array.dtype)

int64


零数组：

In [12]:
a0 = np.zeros((3, 4))
print(a0)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


为１的数组：

In [14]:
a1 = np.ones((4, 5), dtype=int)
print(a1)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


空数组：

In [15]:
a2 = np.empty((3, 4))
print(a2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


间隔数组：

In [19]:
a3 = np.arange(10, 20, 2)
print(a3)

[10 12 14 16 18]


重构数组：

In [21]:
a4 = np.arange(12).reshape((3, 4))
print(a4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


线段：

In [29]:
a5 = np.linspace(1, 10, 20)
print(a5)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
