# 5. numpy的基础运算

## 运算

In [6]:
import numpy as np

a1 = np.array([10, 20, 30, 40])
a2 = np.arange(4)

print(a1)
print(a2)
print(a1+a2)

print(a2 ** 2)
print(10 * np.sin(a1))

[10 20 30 40]
[0 1 2 3]
[10 21 32 43]
[0 1 4 9]
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


## 判断

In [7]:
print(a2 < 3)

[ True  True  True False]


## 普通乘法和矩阵乘法

In [11]:
a = np.array([[1,1],[0,1]])
b = np.arange(4).reshape((2, 2))

print(a)
print(b)
print('----------')
print(a*b)
print(np.dot(a,b))
print(a.dot(b))

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
----------
[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[2 4]
 [2 3]]


## 求和、最小值、最大值

In [13]:
c = np.random.random((2, 4))

print(c)
print(np.sum(c))
print(np.min(c))
print(np.max(c))

[[0.60688527 0.42533853 0.74222835 0.66233367]
 [0.31672463 0.68842121 0.1476412  0.05193221]]
3.641505061127231
0.05193221085186894
0.742228353927082


In [14]:
print(np.sum(c, axis=1))
print(np.min(c, axis=0))
print(np.max(c, axis=1))

[2.43678582 1.20471924]
[0.31672463 0.42533853 0.1476412  0.05193221]
[0.74222835 0.68842121]
