# 7. numpy的索引

In [1]:
import numpy as np

a = np.arange(3, 15)
print(a[3])

6


In [4]:
a = np.arange(3, 15).reshape(3, 4)
print(a)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [5]:
print(a[2])

[11 12 13 14]


In [6]:
print(a[1][2])

9


In [7]:
print(a[1,2])

9


In [8]:
print(a[2, :])

[11 12 13 14]


In [9]:
print(a[:, 2])

[ 5  9 13]


In [14]:
# 迭代行
for row in a:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [15]:
# 迭代列
for column in a.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [16]:
print(a.flatten())

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [21]:
for item in a.flat:
    print(item)

3
4
5
6
7
8
9
10
11
12
13
14
