# 3. Introduction to Neural Prediction: Forward Propagation

- A Simple Network Making a Prediction
- What is a Neural Network and what does it do?
- Making a Prediction with Multiple Inputs
- Making a Prediction with Multiple Outputs
- Making a Prediction wtih Multiple Inputs and Outputs
- Predicting on Predictions

## 3.1 Predict

Data --> Machine --> Prediction

## 3.2 A Simple Neural Network Making a Prediction

In [3]:
weight = 0.1

def neural_network(input, weight):
    prediction = input * weight
    return prediction

number_of_toes = [8.5, 9.5, 10, 9]
input = number_of_toes[0]

pred = neural_network(input, weight)
print(pred)

0.8500000000000001


## 3.3 What is a Neural Network?

What is `input` data?
What is a `prediction` ?
Is this `prediction` always right?
How does the network learn?

## 3.4 What does this Neural Network do?
## 3.5 Making a Prediction with Multiple Inputs

Neural Networks can combine intelligence from multiple datapoints.

In [7]:
def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0

    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

weights = [0.1, 0.2, 0]

def neural_network(input, weights):
    pred = w_sum(input, weights)
    return pred

# This dataset is the current
# status at the beginning of
# each game for the first 4 games
# in a season.

# toes = current number of toes
# wlrec = current games won (percent)
# nfans = fan count (in millions)

toes =  [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(input, weights)

print(pred)

0.9800000000000001


## 3.6 Multiple Inputs - What does this Neural Network do?

**Vector Math** Being able to manipulate vectors is a cornerstone technique for Deep Learning.

```
(8.50 * 0.1) + (0.65 * 0.2) + (1.20 * 0.0) = 0.85 + 0.13 + 0.00 = 0.98
```

## 3.7 Multiple Inputs - Complete Runnable Code

**Numpy Code:**

In [3]:
import numpy as np

weights = [0.1, 0.2, 0]

def neural_network(input, weights):
    pred = input.dot(weights)
    return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.20, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(input, weights)
pred

0.9800000000000001

## 3.8 Making a Prediction with Multiple Outputs
Neural Networks can also make multiple predictions using only a single input.

In [11]:
# Instead of predicting just
# whether the team won or lost,
# now we're also predicting whether
# they are happy/sad AND the percentage
# of the team that is hurt. We are
# making this prediction using only
# the current win/loss record.

def ele_mul(number, vector):
    output = [0, 0, 0]
    assert(len(output)==len(vector))
    for i in range(len(vector)):
        output[i] = number * vector[i]
    return output

weights = [.3, .2, .9]

def neural_network(input, weights):
    pred = ele_mul(input, weights)
    return pred

wlrec = [.65, .8, .8, .9]
input = wlrec[0]
pred = neural_network(input, weights)

print(pred)

[0.195, 0.13, 0.5850000000000001]


## 3.9 Predicting with Multiple Inputs & Outputs
Neural networks can predict multiple outputs given multiple inputs.

In [1]:
weights = [[.1, .1, -0.3],
           [.1, .2, 0.0],
           [0, 1.3, .1]]

def w_sum(a, b):
    assert(len(a)==len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

def vect_mat_mul(vect, matrix):
    assert(len(vect)==len(matrix))
    output = [0,0,0]
    for i in range(len(vect)):
        output[i]=w_sum(vect, matrix[i])
    return output

def neural_network(input, weights):
    pred = vect_mat_mul(input, weights)
    return pred

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [.65, .8, .8, .9]
nfans = [1.2, 1.3, .5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]

pred = neural_network(input, weights)

pred

[0.555, 0.9800000000000001, 0.9650000000000001]

## 3.9 Multiple Inputs & Outputs - How does it work?
It performs 3 independent weighted sums of the input to make 3 predictions.

## 3.10 Predicting on Predictions
Neural networks can be stacked!

In [8]:
ig_wgt = [[.1,.2,-0.1],
          [-0.1,.1,.9],
          [.1,.4,.1]]
hp_wgt = [[.3,1.1,-0.3],
          [.1,.2,0],
          [0,1.3,.1]]
weights = [ig_wgt,hp_wgt]

def neural_network(input, weights):
    hid = vect_mat_mul(input, weights[0])
    pred = vect_mat_mul(hid, weights[1])
    return pred

toes =  [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

# Input corresponds to every entry
# for the first game of the season.

input = [toes[0],wlrec[0],nfans[0]]

pred = neural_network(input, weights)
pred

[0.21350000000000002, 0.14500000000000002, 0.5065]

## 3.11 Numpy Version

In [24]:
import numpy as np

#toes %win #fans
ih_wgt = np.array([
            [0.1, 0.2, -0.1], #hid[0]
            [-0.1,0.1, 0.9], #hid[1]
            [0.1, 0.4, 0.1]]).T #hid[2]
ih_wgt

array([[ 0.1, -0.1,  0.1],
       [ 0.2,  0.1,  0.4],
       [-0.1,  0.9,  0.1]])

In [25]:
# hid[0] hid[1] hid[2]
hp_wgt = np.array([
            [0.3, 1.1, -0.3], #hurt?
            [0.1, 0.2, 0.0], #win?
            [0.0, 1.3, 0.1] ]).T #sad?
hp_wgt

array([[ 0.3,  0.1,  0. ],
       [ 1.1,  0.2,  1.3],
       [-0.3,  0. ,  0.1]])

In [26]:
weights = [ih_wgt, hp_wgt]
weights

[array([[ 0.1, -0.1,  0.1],
        [ 0.2,  0.1,  0.4],
        [-0.1,  0.9,  0.1]]), array([[ 0.3,  0.1,  0. ],
        [ 1.1,  0.2,  1.3],
        [-0.3,  0. ,  0.1]])]

In [29]:
def neural_network(input, weights):
    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred

toes =  np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65,0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0],wlrec[0],nfans[0]])

pred = neural_network(input,weights)
pred

array([0.2135, 0.145 , 0.5065])

## 3.12 A Quick Primer on Numpy