**Chapter 03 Introduction to neural prediction: forward propagation**

> gbtayndb【】sharklasers.com

In this chapter:
- A simple network making a prediction
- What is a neural network, and what does it do?
- Making a prediction with multiple inputs
- Making a prediction with multiple outputs
- Making a prediction with multiple inputs and outputs
- Predicting on predictions

> “I try not to get involved in the business of prediction. It’s a uick way to look like an idiot.”
>
> Warren Ellis comic-book writer, novelist, and screenwriter



# Step 1: Predict

**This chapter is about prediction**

<img algin="center"  src="images/3.1.jpg">

In this chapter, you’ll learn more about what these three different parts of a neural network prediction look like under the hood. Let’s start with the first one: the data. In your first neural network, you’re going to predict one datapoint at a time, like so:

<img algin="center"  src="images/3.2.jpg">

Later, you’ll find that the number of datapoints you process at a time has a significant impact on what a network looks like. You might be wondering, “How do I choose how many datapoints to propagate at a time?” The answer is based on whether you think the neural network can be accurate with the data you give it.

Let’s stick with a single prediction of the likelihood that the baseball team will win:

<img algin="center"  src="images/3.3.jpg">

# A simple neural network making a prediction

<img algin="center"  src="images/3.4.jpg">

In [2]:
weight = 0.1


def neural_network(input, weight):
    prediction = input * weight
    return prediction

<img algin="center"  src="images/3.5.jpg">

In [5]:
number_of_toes = [8.5, 9.5, 10, 9]
input = number_of_toes[0]
pred = neural_network(input, weight)
print(pred)

0.8500000000000001


A neural network knows only what you feed it as input. It forgets everything else. Later, you’ll learn how to give a neural network a “short-term memory” by feeding in multiple inputs at once.

<img algin="center"  src="images/3.6.jpg">

Another way to think about a neural network’s weight value is as a measure of sensitivity between the input of the network and its prediction. If the weight is very high, then even the tiniest input can create a really large prediction! If the weight is very small, then even large inputs will make small predictions. This sensitivity is akin to volume. “Turning up the weight” amplifies the prediction relative to the input: weight is a volume knob!


<img algin="center"  src="images/3.7.jpg">

Note that neural networks don’t predict just positive numbers—they can also **predict negative numbers** and even take **negative numbers as input.**

<img algin="center"  src="images/3.8.jpg">

# Making a prediction with multiple inputs

**Neural networks can combine intelligence from multiple datapoints**

<img algin="center"  src="images/3.9.jpg">
<img algin="center"  src="images/3.10.jpg">
<img algin="center"  src="images/3.11.jpg">
<img algin="center"  src="images/3.12.jpg">


In [17]:
weights = [0.1, 0.2, 0]


def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i]*b[i])

    return output


def neutual_network2(input, weigts):
    pred = w_sum(input, weights)
    return pred


toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]

pred = neutual_network2(input, weights)
print(pred)

0.9800000000000001


# Multiple inputs: What does this neural network do?

**It multiplies three inputs by three knob weights and sums them. T- This is a weighted sum**

The new property here is that, because you have multiple inputs, you have to sum their respective predictions. Thus, you multiply each input by its respective weight and then sum all the local predictions together. This is called a **weighted sum of the input**, or a weighted sum for short. Some also refer to the weighted sum as a **dot product**, as you’ll see.

This new need to process multiple inputs at a time justifies the use of a new tool. It’s called a **vector**, and if you’ve been following along in your Jupyter notebook, you’ve already been using it. A vector is nothing other than a **list of numbers.** 

Anytime you perform a mathematical operation between two vectors of equal length where you pair up values according to their position in the vector (again: position 0 with 0, 1 with 1, and so on), it’s called an **elementwise** operation. Thus **elementwise addition** sums two vectors, and **elementwise multiplication** multiplies two vectors.

> *Being able to manipulate vectors is a cornerstone technique for deep learning. See if you can write functions that perform the following operations:*
>
> `def elementwise_multiplication(vec_a, vec_b)`
>
> `def elementwise_addition(vec_a, vec_b)`
>
> `def vector_sum(vec_a)`
>
> `def vector_average(vec_a)`

The intuition behind how and why a dot product (weighted sum) works is easily one of the most important parts of truly understanding how neural networks make predictions. Loosely stated, a dot product gives you a **notion of similarity** between two vectors. Consider these examples:

```
a = [ 0, 1, 0, 1]    w_sum(a,b) = 0
b = [ 1, 0, 1, 0]
c = [ 0, 1, 1, 0]
d = [.5, 0,.5, 0]
e = [ 0, 1,-1, 0]

w_sum(b,c) = 1
w_sum(b,d) = 1
w_sum(c,c) = 2
w_sum(d,d) = .5
w_sum(c,e) = 0


```

In [19]:
a = [0, 1, 0, 1]
b = [1, 0, 1, 0]
c = [0, 1, 1, 0]
d = [.5, 0, .5, 0]
e = [0, 1, -1, 0]

In [21]:
w_sum(a,b)

0

In [22]:
w_sum(b,c)

1

In [24]:
w_sum(b,d) 

1.0

In [25]:
w_sum(c,c) 

2

In [26]:
w_sum(d,d) 

0.5

In [27]:
w_sum(c,e) 

0

# 5 Multiple inputs: Complete runnable code

The code snippets from this example come together in the following code, which creates and executes a neural network. For clarity, I’ve written everything out using basic properties of Python (lists and numbers). But a better way exists that we’ll begin using in the future.

There’s a Python library called NumPy, which stands for “numerical Python.” It has very efficient code for creating vectors and performing common functions (such as dot products). Without further ado, here’s the same code in NumPy.

In [37]:
import numpy as np

weights = np.array([0.1, 0.2, 0])


def neural_network3(input, weights):
    pred = input.dot(weights)
    return pred


toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])

pred = neural_network3(input, weights)

print(pred)

0.9800000000000001


Both networks should print out `0.98`. Notice that in the NumPy code, you don’t have to create a `w_sum` function. Instead, NumPy has a `dot` function (short for “dot product”) you can call. Many functions you’ll use in the future have NumPy parallels.

# 6 Making a prediction with multiple outputs

**Neural networks can also make multiple predictions using only a single input**

<img algin="center"  src="images/3.13.jpg">
<img algin="center"  src="images/3.14.jpg">
<img algin="center"  src="images/3.15.jpg">
<img algin="center"  src="images/3.16.jpg">

In [60]:
weights = [0.3, 0.2, 0.9]
wlrec = [0.65, 0.8, 0.8, 0.9]
input = wlrec[0]


def ele_mul(number, vector):
    output = [0, 0, 0]
    assert(len(output) == len(vector))

    for i in range(len(vector)):
        output[i] = number*vector[i]
    return output


def neural_network4(input, weights):
    pred = ele_mul(input, weights)
    return pred


pred = neural_network4(input, weights)
print(pred)

[0.195, 0.13, 0.5850000000000001]


# 7 Predicting with multiple inputs and outputs

**Neural networks can predict multiple outputs given multiple inputs**

<img algin="center"  src="images/3.17.jpg">
<img algin="center"  src="images/3.18.jpg">
<img algin="center"  src="images/3.19.jpg">
<img algin="center"  src="images/3.20.jpg">

In [69]:
weights = [[0.1, 0.1, -0.3],
           [0.1, 0.2, 0.0],
           [0.0, 1.3, 0.1]]


def neural_network5(input, weights):
    pred = vect_mat_mul(input, weights)
    return pred


toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]


def w_sum2(a, b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(b)):
        output += (a[i]*b[i])
    return output


def vect_mat_mul(vect, matrix):
    assert(len(vect) == len(matrix))
    output = [0, 0, 0]

    for i in range(len(vect)):
        output[i] = w_sum(vect, matrix[i])

    return output


input = [toes[0], wlrec[0], nfans[0]]
pred = neural_network5(input, weights)

print(pred)

[0.555, 0.9800000000000001, 0.9650000000000001]


# 8 Multiple inputs and outputs: How does it work?

**It performs three independent weighted sums of the input to make - three predictions**

# 9 Predicting on predictions

**Neural networks can be stacked!**

In [79]:
import numpy as np

# toes % win # fans
ih_wgt = np.array([
    [0.1, 0.2, -0.1],  # hid[0]
    [-0.1, 0.1, 0.9],  # hid[1]
    [0.1, 0.4, 0.1]]).T  # hid[2]

# hid[0] hid[1] hid[2]
hp_wgt = np.array([
    [0.3, 1.1, -0.3],  # hurt?
    [0.1, 0.2, 0.0],  # win?
    [0.0, 1.3, 0.1]]).T  # sad?

weights = [ih_wgt, hp_wgt]


def neural_network(input, weights):
    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred


toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])

input
# pred = neural_network(input, weights)
# print(pred)

array([8.5 , 0.65, 1.2 ])

In [82]:
weights[0]

array([[ 0.1, -0.1,  0.1],
       [ 0.2,  0.1,  0.4],
       [-0.1,  0.9,  0.1]])

In [85]:
input.dot(weights[0])

array([0.86 , 0.295, 1.23 ])

In [84]:
pred = neural_network(input,weights)
print(pred)

[0.2135 0.145  0.5065]


# 10 A quick primer on NumPy

**NumPy does a few things for you. Let’s reveal the magic**

In [90]:
import numpy as np

np.array([0,1,2,3])

array([0, 1, 2, 3])

In [91]:
np.array([[0,1,2,3],[4,5,6,7]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [92]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [93]:
np.random.rand(2,5)

array([[0.03975004, 0.65579694, 0.2702395 , 0.058515  , 0.76267758],
       [0.78996906, 0.33966306, 0.75638211, 0.79732993, 0.99568861]])

In [94]:
a = np.zeros((2,4))
b = np.zeros((4,3))
c = a.dot(b)
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [95]:
c.shape

(2, 3)

In [96]:
e = np.zeros((2,1))
f = np.zeros((1,3))
g = e.dot(f)
g

array([[0., 0., 0.],
       [0., 0., 0.]])

In [97]:
g.shape

(2, 3)