# 6. numpy的基础运算2

In [4]:
import numpy as np

a1 = np.arange(2,14).reshape(3,4)
print(a1)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [5]:
# 最小值索引
print(np.argmin(a1))

0


In [6]:
# 最大值索引
print(np.argmax(a1))

11


In [9]:
# 平均值
print(np.mean(a1))
print(a1.mean())
print(np.average(a1))

7.5
7.5
7.5


In [11]:
# 中位数
print(np.median(a1))

7.5


In [13]:
# 累加  a1[n] = a1[0] + a1[1] + ... + a1[n]
print(np.cumsum(a1))

[ 2  5  9 14 20 27 35 44 54 65 77 90]


In [14]:
# 累差
print(np.diff(a1))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [17]:
# 非零
print(np.nonzero(a1))

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))


In [18]:
# 排序
a2 = np.arange(14, 2, -1).reshape(3, 4)
print(a2)
print(np.sort(a2))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


In [19]:
# 矩阵反向
print(np.transpose(a2))

# 常常写为
print(a2.T)

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


In [21]:
# clip 小于 5 的为 5， 大于 9 的为 9
print(np.clip(a2, 5, 9))

[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


In [25]:
# 行(axis=1) 与列(axis=0)
print(a2)
print(np.mean(a2, axis=1))
print(np.mean(a2, axis=0))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[12.5  8.5  4.5]
[10.  9.  8.  7.]
