# 8. numpy的array合并

In [4]:
import numpy as np

a = np.array([1,1,1])
b = np.array([2,2,2])

c = np.vstack((a,b))  # vertical stack
d = np.hstack((a,b))  # horizontal stack
print(c)  
print(d)  

print(a.shape)
print(c.shape)
print(d.shape)

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]
(3,)
(2, 3)
(6,)
