# 10. numpy的 copy & deep copy

## copy

In [2]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
b = a
a[0] = 11
print(a)
print(b)
print(b is a)

[11  2  3  4]
[11  2  3  4]
True


## deep copy

In [5]:
c = a.copy()
a[1]=12
print(a)
print(c)

[11 12  3  4]
[11  2  3  4]
