In [3]:
import numpy as np
from  sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [16]:
iris = datasets.load_iris()

iris_X = iris.data
iris_y = iris.target
iris_X[:2, :]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [18]:
iris_y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [24]:
X_train, X_test, y_train, y_test = train_test_split(iris_X, iris_y, test_size=0.3)

In [26]:
X_test

array([[6.5, 2.8, 4.6, 1.5],
       [5.5, 2.5, 4. , 1.3],
       [4.8, 3. , 1.4, 0.1],
       [5.1, 2.5, 3. , 1.1],
       [4.6, 3.2, 1.4, 0.2],
       [5.7, 2.6, 3.5, 1. ],
       [5. , 3.3, 1.4, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [4.4, 3. , 1.3, 0.2],
       [6.7, 3.1, 4.7, 1.5],
       [5.2, 4.1, 1.5, 0.1],
       [6.2, 2.8, 4.8, 1.8],
       [5.4, 3.4, 1.7, 0.2],
       [5.4, 3.9, 1.3, 0.4],
       [5.7, 3.8, 1.7, 0.3],
       [4.8, 3.4, 1.6, 0.2],
       [6.4, 3.2, 4.5, 1.5],
       [6.7, 3.1, 5.6, 2.4],
       [5.1, 3.3, 1.7, 0.5],
       [6.2, 2.9, 4.3, 1.3],
       [5.5, 2.4, 3.7, 1. ],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5. , 3.4, 1.5, 0.2],
       [7.2, 3. , 5.8, 1.6],
       [5.4, 3.7, 1.5, 0.2],
       [6. , 2.7, 5.1, 1.6],
       [4.3, 3. , 1.1, 0.1],
       [5.7, 4.4, 1.5, 0.4],
       [5.9, 3. , 5.1, 1.8],
       [6. , 2.2, 4. , 1. ],
       [6.3, 2.9, 5.6, 1.8],
       [4.6, 3.4, 1.4, 0.3],
       [6.3, 2.3, 4.4, 1.3],
       [5.7, 2

In [27]:
y_train

array([1, 0, 1, 1, 0, 1, 2, 0, 2, 2, 0, 2, 1, 2, 2, 1, 0, 2, 2, 1, 1, 0,
       2, 1, 0, 1, 2, 0, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1, 0, 1, 2, 2, 1, 0,
       1, 2, 2, 1, 2, 1, 0, 0, 1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 2, 1, 0,
       0, 0, 2, 1, 2, 0, 2, 2, 2, 2, 2, 2, 0, 0, 2, 1, 1, 0, 2, 2, 1, 0,
       1, 2, 0, 0, 0, 2, 1, 1, 1, 0, 1, 0, 1, 2, 2, 2, 2])

In [29]:
y_test

array([1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 1, 2, 0, 1, 1, 0,
       0, 0, 2, 0, 1, 0, 0, 2, 1, 2, 0, 1, 1, 0, 1, 2, 1, 0, 2, 0, 0, 2,
       0])

In [31]:
knn =  KNeighborsClassifier()
knn.fit(X_train, y_train)
knn.predict(X_test)

array([1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 1, 2, 0, 1, 1, 0,
       0, 0, 2, 0, 2, 0, 0, 2, 1, 2, 0, 1, 1, 0, 1, 1, 1, 0, 2, 0, 0, 2,
       0])